name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:  # Include pull request events

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Adjust runner OS if needed
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub (optional)
        if: ${{ env.DOCKER_USERNAME }}
        run: |
          echo "//registry.hub.docker.com:$(docker login --username ${{ env.DOCKER_USERNAME }} --password ${{ env.DOCKER_PASSWORD }} --quiet)" >> $GITHUB_ENV

      - name: Build and Deploy (Make)
        run: |
          make build_deploy

      - name: Check Environment Variable (Optional Podman Deployment)
        run: |
          if [[ -n "${{ env.DEPLOY_METHOD }}" && "${{ env.DEPLOY_METHOD }}" == "podman" ]]; then
            echo "Deploying to Proxmox Container (Podman)"
          else
            echo "Deploying Infrastructure (Terraform - VM)"
          fi

      - name: Deploy Infrastructure (Terraform - VM)
        if: github.event.name == 'push' && github.base_branch == 'main' && !${{ env.DEPLOY_METHOD }} || ${{ env.DEPLOY_METHOD }} == "vm"
        env:
          PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
          PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
        run: |
          make terraform_vm

      - name: Deploy to Proxmox Container (Podman)
        if: github.event.name == 'push' && github.base_branch == 'main' && ${{ env.DEPLOY_METHOD }} == "podman"
        env:
          PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
          PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
        run: |
          make podman_deploy

